-- MySQL Script generated by MySQL Workbench
-- Fri Nov 25 10:02:06 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema planx
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `planx` ;

-- -----------------------------------------------------
-- Schema planx
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `planx` DEFAULT CHARACTER SET utf8 ;
USE `planx` ;

-- -----------------------------------------------------
-- Table `planx`.`t_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `planx`.`t_users` (
  `id` VARCHAR(64) NOT NULL,
  `username` VARCHAR(32) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `salt` VARCHAR(64) NULL,
  `displayName` VARCHAR(32) NOT NULL,
  `description` TEXT NULL,
  `phone` VARCHAR(32) NULL,
  `email` VARCHAR(64) NULL,
  `provider` VARCHAR(32) NULL,
  `imageUrl` VARCHAR(256) NULL,
  `thumbUrl` VARCHAR(256) NULL,
  `roles` VARCHAR(64) NULL,
  `resetToken` VARCHAR(64) NULL,
  `tokenCreated` BIGINT NULL,
  `updated` BIGINT NULL,
  `created` BIGINT NULL,
  `status` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `resetToken_idx` (`resetToken` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `planx`.`t_medias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `planx`.`t_medias` (
  `id` VARCHAR(64) NOT NULL,
  `posterId` VARCHAR(64) NULL,
  `userId` VARCHAR(64) NOT NULL,
  `mediaUrl` VARCHAR(256) NULL,
  `thumbUrl` VARCHAR(256) NULL,
  `type` INT NULL,
  `width` INT NULL,
  `height` INT NULL,
  `updated` BIGINT NULL,
  `created` BIGINT NULL,
  `status` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `userId_idx` (`userId` ASC, `created` ASC),
  INDEX `posterId_idx` (`posterId` ASC, `created` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `planx`.`t_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `planx`.`t_comments` (
  `id` VARCHAR(64) NOT NULL,
  `userId` VARCHAR(64) NOT NULL,
  `targetId` VARCHAR(64) NOT NULL,
  `replyId` VARCHAR(64) NULL,
  `content` TEXT NULL,
  `updated` BIGINT NULL,
  `created` BIGINT NULL,
  `status` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `userId_idx` (`userId` ASC, `created` ASC),
  INDEX `targetId_idx` (`targetId` ASC, `created` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `planx`.`t_posters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `planx`.`t_posters` (
  `id` VARCHAR(64) NOT NULL,
  `userId` VARCHAR(64) NULL,
  `title` VARCHAR(64) NULL,
  `content` TEXT NULL,
  `type` INT NULL,
  `votes` INT NULL DEFAULT 0,
  `updated` BIGINT NULL,
  `created` BIGINT NULL,
  `status` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `userId_idx` (`userId` ASC, `created` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `planx`.`t_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `planx`.`t_tags` (
  `id` VARCHAR(64) NOT NULL,
  `posterId` VARCHAR(64) NOT NULL,
  `tag` VARCHAR(64) NULL,
  `created` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `tag_idx` (`tag` ASC, `created` ASC),
  INDEX `posterId_idx` (`posterId` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
